// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crudelicious.Models;

namespace crudelicious.Migrations
{
    [DbContext(typeof(crudeliciousContext))]
    [Migration("20190215202253_crudeliciousMigration")]
    partial class crudeliciousMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("crudelicious.Models.MyModel", b =>
                {
                    b.Property<int>("MyModelId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Calories");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Tastiness");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("chefName")
                        .IsRequired();

                    b.Property<string>("dishName")
                        .IsRequired();

                    b.HasKey("MyModelId");

                    b.ToTable("mymodels");
                });
#pragma warning restore 612, 618
        }
    }
}
